=head1 NAME

Net::CLI::Interact::Manual::Phrasebook - List of Supported CLIs

=head1 INTRODUCTION

The bundled phrasebook includes support for a variety of network device CLIs.
Many were contributed by users of the module. If you set up a new CLI
dictionary, please consider contributing it back! The phrasebook specification
is given in L<Net::CLI::Interact::Phrasebook>.

For each supported CLI, there is a name which must be passed in the
C<personality> option to L<Net::CLI::Interact>'s C<new()> method. After that,
you can call the included Macros, and the module will use the included Prompt
to match the current state of the CLI. More information is available in the
L<Tutorial|Net::CLI::Interact::Manual::Tutorial> and
L<Cookbook|Net::CLI::Interact::Manual::Cookbook>.

Below is a list of all current bundled CLI dictionaries. Each lists its name,
the available Prompts, Macros and Continuations, and from which other CLI
dictionaries it inherits.

 IOS       # Cisco IOS
 CatOS     # for older, pre-IOS Cisco devices
 
 PIXOS     # for PIX OS-based devices
 PIXOS7    # Slightly different commands from other PIXOS versions
 FWSM      # currently the same as 'PIXOS'
 FWSM3     # for FWSM Release 3.x devices (slightly different to FWSM 2.x)
 
 JunOS     # Juniper JUNOS support
 HP        # HP support
 Nortel    # Nortel support
 ExtremeOS # Extreme Networks support

=head1 PERSONALITIES

=head2 Cisco

This personality goes by the name of C<cisco> and provides a basis for many
other CLI dictionaries.

Prompts are C<basic>, C<privileged>, C<configure>, C<user>, and C<pass>.

Macros are C<begin_privileged>, C<end_privileged>, C<begin_configure>,
C<end_configure>, and C<disconnect>.

=head2 CatOS

This personality goes by the name of C<catos> and inherits from the C<cisco>
dictionary.

Additionally it provides the C<privileged> Prompt.

Additionally it also provides the C<paging> Macro to set the terminal page
size.

=head2 ExtremeOS

This personality goes by the name of C<extremeos> and inherits from the
C<cisco> dictionary.

Additional Prompts are C<basic>, C<privileged>, C<configure>, C<user>, and
C<pass>.

Additional Macros are C<begin_privileged>, C<end_privileged>, and
C<disconnect>.

=head2 IOS

This personality goes by the name of C<ios> and inherits from the C<cisco>
dictionary.

Additionally it provides the C<paging> Macro to set the terminal page size.

=head2 HP

This personality goes by the name of C<hp> and inherits from the C<cisco>
dictionary.

Additionally it provides the C<basic> and C<user> Prompts.

=head2 JunOS

This personality goes by the name of C<junos> and inherits from the C<cisco>
dictionary.

Additionally it provides the C<privileged>, C<configure>, and C<user> Prompts.

Additionally it also provides the C<begin_configure> and C<paging> Macros.

=head2 Nortel

This personality goes by the name of C<nortel> and inherits from the C<cisco>
dictionary.

Additionally it provides the C<user> Prompt.

=head2 PIXOS

This personality goes by the name of C<pixos> and inherits from the C<cisco>
dictionary.

Additionally it provides the C<paging> Macro to set the terminal page size.

It can be used in its own right for Cisco PIX firewalls, but is
also used as a base for other dictionaries.

=head2 PIXOS 7

This personality goes by the name of C<pixos7> and inherits from the C<pixos>
dictionary.

Additionally it provides the C<paging> Macro to set the terminal page size.

=head2 FWSM

This personality goes by the name of C<fwsm> and inherits from the C<pixos>
dictionary.

It provides no further functionality, as Cisco FWSM software version 1 and 2
was the same as the PIX OS.

=head2 FWSM 3

This personality goes by the name of C<fwsm3> and inherits from the C<pixos>
dictionary.

Additionally it provides the C<paging> Macro to set the terminal page size.

=cut
